### ISSUE TITLE
Intermittent CORS errors and 503 responses (With CSP already configured)

### ISSUE THREAD

**Issue by dlanz** [microsoft/clarity#293]
Hi, 

I followed the "Install Manually" instructions here: https://learn.microsoft.com/en-us/clarity/clarity-setup
And I added the appropriate CSP entries as outlined here: https://learn.microsoft.com/en-us/clarity/clarity-csp
And I'm also only permitting Clarity to perform any actions after the user provides consent by following the steps outlined here: https://learn.microsoft.com/en-us/clarity/cookie-consent

And I can confirm the _clck cookie is set as expected after providing consent.

For the most part, Clarity appears to be working perfectly fine. I have many results showing up in my dashboard.

But I'm intermittently getting CORS errors and 503 responses. Sometimes I get them, other times everything seems fine.
![image](https://user-images.githubusercontent.com/4248825/198330667-fa1cd650-6d4e-4727-8572-48e9a88e2f36.png)

Among other domains, the CSP on my page includes:
Content-Security-Policy: default-src 'self' 'unsafe-inline' *.clarity.ms clarity.ms c.bing.com

This post seems to be my exact behavior, but a solution was never posted. The OP says they never figured it out, but it eventually stopped happening. However, one of the suggestions was to configured a CSP properly, which I've done and still getting the errors.
https://github.com/microsoft/clarity/issues/59

Just want to note, I have another oddity involving the first occurrence of the left click mouse event. I don't intent to ask about that here and now, but figured I'd mention it in case it was relevant for some reason I'm unaware of.

**Comment by ClaritySupport** [comment]
@dlanz , We are Clarity support team. Could you please share link to page on your website where Clarity was installed and you are seeing above errors to investigate further.

**Comment by dlanz** [comment]
Sure, so it is intermittent, but I have received these 503/CORS errors on this particular page previously:
https://my.centralsemi.com/

**Comment by ClaritySupport** [comment]
Hi Dan,

Thanks for sharing details. We are not seeing any error on your website. Is there any specific conditions to repro that issue?

Adding Clarity to your default-src directive should resolve the issue.

Thanks,
Clarity Support Team
Visit our docs!: https://docs.microsoft.com/en-us/clarity<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fclarity&data=05%7C01%7Cv-vidasa%40microsoft.com%7C343fe08f40a94e184c6408da28fedd21%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637867372409365494%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q1zklwmipOGmVmg01HjPFwTVAwft75whSRoB8fFF%2BoY%3D&reserved=0>
***@***.******@***.***>
***@***.***

Confidentiality note: This e-mail, and any attachment to it, contains privileged and confidential information intended only for the use of the individual(s) or entity named in the e-mail.  If the reader of the e-mail is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that reading it is strictly prohibited.  If you have received this e-mail in error, please immediately return it to the sender and delete it from your system.

**Comment by dlanz** [comment]
Yeah, it's intermittent.  Sometimes it happens and sometimes it doesn't. I haven't been able to pin down any commonality among the times where the errors occur.

Is there some set of actions I should take the next time it occurs which might help pin down the issue? Would a HAR file dump be helpful?

**Comment by ClaritySupport** [comment]
Hi Dan,

Yes, error logs would be helpful to investigate issue. Please do share HAR file attachment if it occurs next time.

Thanks,
Clarity Support Team
Visit our docs!: https://docs.microsoft.com/en-us/clarity<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fclarity&data=05%7C01%7Cv-vidasa%40microsoft.com%7C343fe08f40a94e184c6408da28fedd21%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637867372409365494%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q1zklwmipOGmVmg01HjPFwTVAwft75whSRoB8fFF%2BoY%3D&reserved=0>
***@***.******@***.***>
***@***.***

Confidentiality note: This e-mail, and any attachment to it, contains privileged and confidential information intended only for the use of the individual(s) or entity named in the e-mail.  If the reader of the e-mail is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that reading it is strictly prohibited.  If you have received this e-mail in error, please immediately return it to the sender and delete it from your system.

**Comment by dlanz** [comment]
@ClaritySupport 

I had the the 503 CORS errors occur again, but on a different site, intranet only though. Attached is the exported HAR file.  I went through and remove some information, nothing pertaining to Clarity though.

[har.txt](https://github.com/microsoft/clarity/files/10035572/har.txt)

Note, I had to rename to .txt in order to attach.

**Comment by dlanz** [comment]
This issue is still occurring, are there other error logs I can provide which might help?

**Comment by ClaritySupport** [comment]
Hi Dan,

We don't see any errors on your website console.Could you please share below details to assist you further.


  1.  Link to page on your website showing the error.
  2.  Browser details.

Thanks,
Clarity Support Team
Visit our docs!: https://docs.microsoft.com/en-us/clarity<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fclarity&data=05%7C01%7Cv-vidasa%40microsoft.com%7C343fe08f40a94e184c6408da28fedd21%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637867372409365494%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q1zklwmipOGmVmg01HjPFwTVAwft75whSRoB8fFF%2BoY%3D&reserved=0>
***@***.******@***.***>
***@***.***

Confidentiality note: This e-mail, and any attachment to it, contains privileged and confidential information intended only for the use of the individual(s) or entity named in the e-mail.  If the reader of the e-mail is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that reading it is strictly prohibited.  If you have received this e-mail in error, please immediately return it to the sender and delete it from your system.

**Comment by dlanz** [comment]
Yeah, the issue is intermittent, most of the time it works fine.  That's why I provided the HAR export of one of the times it did NOT work.

In the har.txt previously posted, do a search for `"status": 503`.  You'll see there are 6 total resources which received a 503 response code. All 6 are on the https://a.clarity.ms/collect end-point.

User agent at the time of the har.txt file was:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

Current version of Chrome is (has changed since the har.txt was generated):
Version 108.0.5359.125 (Official Build) (64-bit)

I do not remember what version of Chrome I had when I generated the har.txt.  But the same issues have continued to occur on the current version.

@ClaritySupport

**Comment by ClaritySupport** [comment]
Hi Dan,

Apologies for delay. 503s don't have CSP headers, so they will expectedly show up as CSP errors. They can happen intermittently during minor service outages and health degradations. I don't think the you mentioned you found 6 instances of these 503s, but it is unclear what the time period is. 6 in a month would be normal, 6 every day is not ok.

Are you seeing these 503s consistently, or is it a rare event? Some tiny level of 503s is inevitable and should not impact your Clarity or website experience significantly. But if you are constantly finding these 503s happening, please share their project id or website url to investigate further.


Thanks,
Clarity Support Team
Visit our docs!: https://docs.microsoft.com/en-us/clarity<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fclarity&data=05%7C01%7Cv-vidasa%40microsoft.com%7C343fe08f40a94e184c6408da28fedd21%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637867372409365494%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q1zklwmipOGmVmg01HjPFwTVAwft75whSRoB8fFF%2BoY%3D&reserved=0>
***@***.******@***.***>
***@***.***

Confidentiality note: This e-mail, and any attachment to it, contains privileged and confidential information intended only for the use of the individual(s) or entity named in the e-mail.  If the reader of the e-mail is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that reading it is strictly prohibited.  If you have received this e-mail in error, please immediately return it to the sender and delete it from your system.

**Comment by dlanz** [comment]
The 6 instances in the HAR file I provided occurred within a minute or two. It usually happens in clusters like that when it does occur though. As far as how often these clusters occur, it's not too frequently. But frequently enough that I noticed it happening repeatedly. 

Is it correct that:
1. These 503's cannot disrupt anything on my site other than clarity.
2. These 503's have more to do with your servers than my site.

If the above two statements are true, then I am content with these occasionally occurring, no need to investigate further.

**Comment by ClaritySupport** [comment]
Hi Dan,

The both statements are true. 500s from Clarity servers cannot disrupt the Web page in any way.


Thanks,
Clarity Support Team
Visit our docs!: https://docs.microsoft.com/en-us/clarity<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fclarity&data=05%7C01%7Cv-vidasa%40microsoft.com%7C343fe08f40a94e184c6408da28fedd21%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637867372409365494%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q1zklwmipOGmVmg01HjPFwTVAwft75whSRoB8fFF%2BoY%3D&reserved=0>
***@***.******@***.***>
***@***.***

Confidentiality note: This e-mail, and any attachment to it, contains privileged and confidential information intended only for the use of the individual(s) or entity named in the e-mail.  If the reader of the e-mail is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that reading it is strictly prohibited.  If you have received this e-mail in error, please immediately return it to the sender and delete it from your system.

**Comment by eddivalen** [comment]
Hey @ClaritySupport , I'm having the same problem on my website, and we're not using CSP. This issue seems to be specific to Safari.
![Screenshot 2023-11-04 121322](https://github.com/microsoft/clarity/assets/8193094/f670f152-bd97-423b-a7af-f9ec728c8b39)


This is the page where it's happening : [checkout](https://members.clickminded.com/checkouts/agency-growth-toolkit)

**Comment by ClaritySupport** [comment]
@eddivalen,The console errors in Safari are harmless (and unavoidable). The actual javascript is not throwing in its execution thread, Safari just logs attempts to access iframes like this as console errors.

**Comment by alexcarpenter** [comment]
Also seeing these issues popup for me as well. Not specific to Safari either, seeing it in Chrome as well.
