### ISSUE TITLE
Clarity v 0.8.6 Causing CssStyleSheet().Replace to break

### ISSUE THREAD

**Issue by yehuda-MoonShot** [microsoft/clarity#819]
Please also add all relevant labels from the list of existing ones. 

**Describe the bug**
Clarity's interception of the CssStyleSheet prototype is causing code that relies on the CssStyleSheet to break with 
```
clarity.js:2 Uncaught SecurityError: Failed to read a named property 'clarityOverrides' from 'Window': Blocked a frame with origin "https://www.example.com" from accessing a cross-origin frame.
    at Qe.u.lean.u.lite.t.CSSStyleSheet.t.CSSStyleSheet.t.clarityOverrides.replace.CSSStyleSheet.replace (clarity.js:2:22885)
    at <anonymous>:1:11
```

**Repro Steps**
Go to a website that has Clarity 0.8.6 installed run the following code in the console
```
let css = new CSSStyleSheet()
await css.replace('.background{background: blue;}')
```

**Browser info:**
Any browser but I reproduced on chrome 135.0.7049.96 

**Going Forward:**
If you're intercepting/patching base JS functionality every aspect of your change should be wrapped in try catch so that if your code fails it doesn't break code that relies on that JS.

**Comment by broskisworld** [comment]
This is causing lots of problems with Shopify sites -- breaking some apps and theme styles. Can we get a fix ASAP?

**Comment by yehuda-MoonShot** [comment]
> This is causing lots of problems with Shopify sites -- breaking some apps and theme styles. Can we get a fix ASAP?

Not just shopify we're seeing this across every single one of our clients.

**Comment by pauldraper** [comment]
https://github.com/microsoft/clarity/commit/4344e2cecea5617b16bc7347332dddf11a9f0ea3

@ender336

**Comment by MustafaLeithy** [comment]
Thanks for providing this feedback. This change has been unshipped. It should be resolved now.

**Comment by yehuda-MoonShot** [comment]
> Thanks for providing this feedback. This change has been unshipped. It should be resolved now.

Hi @MustafaLeithy could you clarify what you mean by unshipped. I see the package is still available on https://www.npmjs.com/package/clarity-js?activeTab=versions. While the errors have slowed we are still getting errors intermittently

**Comment by pauldraper** [comment]
@yehuda-MoonShot I believe that means that the clarity.ms URL is not using the latest version anymore.

**Comment by nairmanu** [comment]
Fix to address this is available in the latest release. Please let us know if you are still facing the issue in latest version of clarity-js
